version: "3"

services:
  bot:
    image: node:20-alpine3.16
    working_dir: /app
    volumes:
      - .:/app
    command: ["node", "./src/index.js"]
    environment:
      - DISCORD_TOKEN=your_discord_token_here
